name: Auto Redeploy
run-name: "@${{ github.actor }} was pushed up a new update. Auto-Redeploy START!"
on: 
  workflow_dispatch:
  push:
    branches:
    - 'main'
  
jobs:
  Automate-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: wanassanan/itb-kk-database:latest
      - name: Trigger redeploy
        run: 'curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" https://intproj23.sit.kmutt.ac.th/pl1/watchtower/v1/update'
